### ISSUE TITLE
Problem in using in conjunction with yii2-dynamicform

### ISSUE THREAD

**Issue by flavio-pessoa** [yiibr/yii2-correios#8]
Plugin URL: https://github.com/wbraganca/yii2-dynamicform

When using the plugin with the other plugin yii2-dynamicform, only the first field works, being the others when clicking the button to search simply does not fill with the data.

**Comment by georgezim85** [comment]
I suggest you to use google API
http://www.princiweb.com.br/blog/programacao/google-apis/google-maps-api-v3-busca-de-endereco-e-autocomplete.html

**Comment by leandrogehlen** [comment]
@flavio-pessoa, Você chegou a identificar o problema, se se ocorre algum erro de javascript?

**Comment by flavio-pessoa** [comment]
Não ocorre erro e do componente dynamicform, que adiciona nos outros endereços a chamada javascript do seu plugins. isso também ocorre não somente com o seu mas com vários outros plugins se forem usados com o plugin do wbraganca/yii2-dynamicform, vou falar com wbraganca para ver isso.

**Comment by flavio-pessoa** [comment]
Resolvi assim tive que colocar manualmente a chamada ao metodo.

$(".dynamicform_wrapper").on("afterInsert", function(e, item) {
    console.log("afterInsert");
	var inputmask_cep_endereco2 = {"mask":"99999-999"};
	$("#funcionarioendereco-1-cep_endereco").inputmask(inputmask_cep_endereco2);
	$('#funcionarioendereco-1-cep_endereco').cep({"action":"/xxx/web/cadastro/funcionario/addressSearch","fields":{"location":"funcionarioendereco-1-logradouro_endereco","district":"funcionarioendereco-1-bairro_endereco","city":"funcionarioendereco-1-cidade_endereco","state":"funcionarioendereco-1-uf_endereco","cep":"funcionarioendereco-1-cep_endereco"},"queryParam":"_cep"});
});

**Comment by leandrogehlen** [comment]
Acredito que o problema ocorre por que a extensao yii2-dynamicform copia elementos do formulario, porem nao clona todos os plugin vinculado ao elemento que está sendo clonado.
Sendo assim este problema não é válido aqui
